name: Windows CI (Fork)

on:
  push:
    branches: [ "main", "windows-ci-config" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build LLVM (${{ matrix.build_type }})
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release, Debug, RelWithDebInfo, MinSizeRel]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Setup Visual Studio Environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64

    - name: Install Ninja
      run: choco install ninja

    - name: Configure CMake
      shell: cmd
      run: |
        cmake -S llvm -B build -G Ninja ^
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ^
          -DLLVM_ENABLE_PROJECTS="llvm;clang" ^
          -DLLVM_TARGETS_TO_BUILD="X86" ^
          -DLLVM_OPTIMIZED_TABLEGEN=ON ^
          -DLLVM_PARALLEL_LINK_JOBS=1 ^
          -DLLVM_ENABLE_LTO=OFF

    - name: Build
      run: ninja -C build llvm-tblgen clang-tblgen clang

    - name: Archive Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: LLVM-Windows-${{ matrix.build_type }}-Artifacts
        path: |
          build/bin
          build/lib
        retention-days: 3